# Generated by Django 3.1.8 on 2021-07-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolhall', '0003_auto_20210723_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
