# Generated by Django 3.1.8 on 2021-07-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolhall', '0004_auto_20210723_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='table',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
