# Generated by Django 3.1.8 on 2021-07-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolhall', '0005_auto_20210723_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.RemoveField(
            model_name='table',
            name='time',
        ),
    ]
