# Generated by Django 3.1.8 on 2021-07-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolhall', '0007_auto_20210723_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
